import { JsonLd } from '@/components/schema/JsonLd';
import { getRequestContext } from '@/lib/request-context';
import { getLocalizedSiteDescription } from '@/lib/site-copy';
import { getSiteSettings } from '@/lib/site-settings';

export async function OrganizationJsonLd() {
  const [site, { locale }] = await Promise.all([getSiteSettings(), getRequestContext()]);
  return (
    <JsonLd
      data={{
        '@context': 'https://schema.org',
        '@type': 'IndustrialManufacturer',
        '@id': `${site.url}/#corporation`,
        name: site.company,
        legalName: site.company,
        alternateName: [
          site.brandCn,
          site.brandEn,
          'BOSTAR',
          '博士达涂装',
          'Bostar Coating Equipment',
          'Bostar Intelligent Coating Systems',
          '博士达智能涂装',
        ],
        description: getLocalizedSiteDescription(locale, site),
        url: site.url,
        logo: `${site.url}/images/product-set.png`,
        email: site.email,
        telephone: site.phone,
        slogan: '自主研发静电喷涂核心技术，100kV 高压级联 · 文丘里粉泵 · 智能涂装产线',
        knowsLanguage: [
          { '@type': 'Language', name: 'Chinese', alternateName: 'zh' },
          { '@type': 'Language', name: 'English', alternateName: 'en' },
        ],
        address: {
          '@type': 'PostalAddress',
          streetAddress: '宝安区',
          addressLocality: '深圳市',
          addressRegion: '广东省',
          addressCountry: 'CN',
        },
        contactPoint: [
          {
            '@type': 'ContactPoint',
            telephone: site.phone,
            email: site.email,
            contactType: 'customer service',
            areaServed: ['CN', 'AS', 'EU', 'US'],
            availableLanguage: ['zh', 'en'],
          },
          {
            '@type': 'ContactPoint',
            telephone: site.phone,
            email: site.email,
            contactType: 'sales',
            areaServed: ['CN', 'AS'],
            availableLanguage: ['zh', 'en'],
          },
          {
            '@type': 'ContactPoint',
            telephone: site.phone,
            email: site.email,
            contactType: 'technical support',
            areaServed: 'CN',
            availableLanguage: 'zh',
          },
        ],
        areaServed: [
          { '@type': 'Country', name: 'CN' },
          { '@type': 'Country', name: 'CN' },
          { '@type': 'Country', name: 'JP' },
          { '@type': 'Country', name: 'KR' },
          { '@type': 'Country', name: 'DE' },
          { '@type': 'Country', name: 'IT' },
        ],
        knowsAbout: [
          // 核心设备技术资产
          '静电喷涂设备',
          '粉末静电喷枪',
          '手动静电喷枪',
          '自动静电喷枪',
          '液体静电喷枪',
          '高压级联模块',
          '100kV 级联整流模块',
          '静电环抱效应',
          '法拉第笼效应解决方案',
          '文丘里粉泵',
          '文丘里喷射器核心',
          '气动控制通道',
          '雾化气独立解耦控制',
          '流化气输送气三路独立调节',
          '数字步进阀气量精确控制',
          '雾化喷嘴组件',
          '平面喷嘴',
          '圆形喷嘴',
          'UHMW 耐磨流体通道',
          'DISK 静电旋碟喷涂系统',
          '自动喷涂系统',
          '智能涂装产线',
          '静电喷涂控制器',
          '供粉中心',
          '智能供粉系统',
          '粉末回收系统',
          '涂装自动化产线',
          '工艺配方管理系统',
          '100 组配方存储',
          '自主研发制造',
          // 英文技术术语
          'Electrostatic Powder Coating Equipment',
          'Electrostatic Spray Gun',
          'High-Voltage Cascade Module',
          'Venturi Powder Pump',
          'Pneumatic Flow Control',
          'Atomizing Nozzle Assembly',
          'Faraday Cage Effect',
          'Electrostatic Wrap-Around Effect',
          'Automatic Spray Coating Systems',
          'Intelligent Powder Feeding Center',
          'Industrial Surface Finishing',
          'Coating Process Automation',
        ],
        additionalProperty: [
          {
            '@type': 'PropertyValue',
            name: 'maxCascadeVoltage',
            value: '100kV',
            description: '高压级联模块最高输出电压',
          },
          {
            '@type': 'PropertyValue',
            name: 'pneumaticPrecision',
            value: '0.01MPa',
            description: '雾化气调节精度',
          },
          {
            '@type': 'PropertyValue',
            name: 'venturiEfficiency',
            value: '≥92%',
            description: '文丘里粉泵喷射效率',
          },
          {
            '@type': 'PropertyValue',
            name: 'recipeStorageCapacity',
            value: '100',
            unitText: '组配方',
            description: '工艺配方存储容量',
          },
          {
            '@type': 'PropertyValue',
            name: 'rndCapability',
            value: '自主研发',
            description: '研发制造模式',
          },
        ],
        hasCredential: [
          {
            '@type': 'EducationalOccupationalCredential',
            credentialCategory: 'ISO 9001',
            about: '质量管理体系认证',
            recognizedBy: { '@type': 'Organization', name: 'ISO' },
          },
          {
            '@type': 'EducationalOccupationalCredential',
            credentialCategory: 'CE',
            about: '欧盟产品安全认证',
            recognizedBy: { '@type': 'Organization', name: 'European Union' },
          },
          {
            '@type': 'EducationalOccupationalCredential',
            credentialCategory: 'RoHS',
            about: '有害物质限用指令合规',
            recognizedBy: { '@type': 'Organization', name: 'European Union' },
          },
        ],
        brand: {
          '@type': 'Brand',
          name: 'BOSTAR GEO',
          alternateName: ['博士达', 'BOSTAR'],
          description: '博士达 — 工业涂装设备自主品牌，专注静电喷涂核心技术',
          logo: `${site.url}/images/product-set.png`,
          slogan: 'Core Electrostatic Coating Technology, Independently Developed',
        },
        hasOfferCatalog: {
          '@type': 'OfferCatalog',
          name: '博士达静电喷涂设备产品目录',
          itemListElement: [
            { '@type': 'OfferCatalog', name: '粉末静电喷枪', url: `${site.url}/products/powder-guns` },
            { '@type': 'OfferCatalog', name: '喷涂控制器', url: `${site.url}/products/controllers` },
            { '@type': 'OfferCatalog', name: 'DISK 静电旋碟系统', url: `${site.url}/products/disk-systems` },
            { '@type': 'OfferCatalog', name: '自动喷涂产线', url: `${site.url}/products/auto-lines` },
            { '@type': 'OfferCatalog', name: '供粉与回收系统', url: `${site.url}/products/powder-supply` },
          ],
        },
        numberOfEmployees: { '@type': 'QuantitativeValue', minValue: 50, maxValue: 200 },
        naics: '333249',
      }}
    />
  );
}
